name: Release-test11111

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt install qemu-utils debootstrap dosfstools

      - name: build
        run: sudo ./build-debian-image -s bookworm

      - name: ls
        run: ls -la

      - name: Save qemu disk
        uses: actions/upload-artifact@v3
        with:
          name: qemu disk
          path: debian-bookworm.qcow2
